import React, { useState } from 'react';
import { Bell, Check, X } from 'lucide-react';

const styles = `.notification-control{position:relative}.notification-trigger{position:relative;display:grid;place-items:center;width:36px;height:36px;border:1px solid #E3E7EF;border-radius:10px;background:#F3F5F9;color:#12213F;cursor:pointer}.notification-dot{position:absolute;top:6px;right:6px;width:7px;height:7px;border:1.5px solid #fff;border-radius:50%;background:#EF5B4E}.notification-panel{position:absolute;z-index:5;top:44px;right:0;width:310px;border:1px solid #E3E7EF;border-radius:12px;background:#fff;box-shadow:0 12px 28px rgba(18,33,63,.14)}.notification-head{display:flex;align-items:center;justify-content:space-between;padding:14px 15px;border-bottom:1px solid #E3E7EF}.notification-title{margin:0;color:#12213F;font:700 13px 'Sora',sans-serif}.notification-close{border:0;background:transparent;color:#697086;cursor:pointer}.notification-item{display:flex;gap:10px;padding:13px 15px;border-bottom:1px solid #F0F2F6}.notification-item:last-child{border-bottom:0}.notification-mark{width:8px;height:8px;margin-top:5px;border-radius:50%;background:#3E7BFA;flex-shrink:0}.notification-copy{color:#12213F;font-size:12px;line-height:1.4}.notification-meta{margin-top:4px;color:#9AA1B4;font-size:10.5px}.notification-footer{display:flex;align-items:center;gap:6px;padding:11px 15px;border-top:1px solid #E3E7EF;color:#0C8C6B;font-size:11px;font-weight:700}`;
const defaults = [{ id: 1, text: 'Route 08 has been delayed by 14 minutes.', meta: 'Operations · 8 mins ago' }, { id: 2, text: 'COD settlement SET-00482 is ready for review.', meta: 'Finance · 22 mins ago' }, { id: 3, text: 'New pickup scheduled for Colombo Hub.', meta: 'Pickup desk · 1 hour ago' }];

export default function NotificationBell({ notifications = defaults }) {
	const [open, setOpen] = useState(false);
	return <div className="notification-control"><style>{styles}</style><button type="button" className="notification-trigger" aria-label="Notifications" onClick={() => setOpen((current) => !current)}><Bell size={17} />{notifications.length ? <span className="notification-dot" /> : null}</button>{open ? <div className="notification-panel"><div className="notification-head"><h3 className="notification-title">Notifications</h3><button type="button" className="notification-close" onClick={() => setOpen(false)}><X size={15} /></button></div>{notifications.map((item) => <div className="notification-item" key={item.id}><span className="notification-mark" /><div className="notification-copy">{item.text}<div className="notification-meta">{item.meta}</div></div></div>)}<div className="notification-footer"><Check size={13} /> All caught up with current activity</div></div> : null}</div>;
}
