import React, { useState } from 'react';

const styles = `.template-editor{padding:20px;border:1px solid #E3E7EF;border-radius:14px;background:#fff}.template-editor h2{margin:0 0 18px;color:#12213F;font:700 15px 'Sora',sans-serif}.template-grid{display:grid;gap:14px}.template-field{display:grid;gap:7px}.template-field label{color:#697086;font-size:11px;font-weight:700;letter-spacing:.04em;text-transform:uppercase}.template-field input,.template-field select,.template-field textarea{width:100%;border:1px solid #E3E7EF;border-radius:10px;background:#F9FAFC;color:#12213F;padding:10px 12px;font-size:13px;outline:none}.template-field textarea{min-height:150px;resize:vertical;line-height:1.5}.template-field input:focus,.template-field select:focus,.template-field textarea:focus{border-color:#3E7BFA;box-shadow:0 0 0 3px rgba(62,123,250,.12)}.template-help{color:#697086;font-size:11px}.template-variables{display:flex;flex-wrap:wrap;gap:6px}.template-variable{border:1px solid #E3E7EF;border-radius:7px;padding:5px 7px;background:#fff;color:#2453B8;font:11px 'IBM Plex Mono',monospace}.template-actions{display:flex;justify-content:flex-end;gap:10px;margin-top:18px}.template-actions button{border:1px solid #E3E7EF;border-radius:10px;padding:10px 14px;font-size:12px;font-weight:700;cursor:pointer}.template-cancel{background:#fff;color:#12213F}.template-save{background:#12213F;color:#fff;border-color:#12213F!important}`;
const defaults = { name: 'Shipment delivered', channel: 'Email', subject: 'Your shipment {{trackingNumber}} was delivered', body: 'Hello {{customerName}},\n\nYour shipment {{trackingNumber}} has been delivered successfully.\n\nThank you for using EGOTECH.' };

export default function TemplateEditor({ initialValues = defaults, onSubmit = () => {}, onCancel = () => {} }) {
	const [values, setValues] = useState({ ...defaults, ...initialValues });
	const update = (event) => setValues((current) => ({ ...current, [event.target.name]: event.target.value }));
	return <div className="template-editor"><style>{styles}</style><h2>Notification template</h2><form onSubmit={(event) => { event.preventDefault(); onSubmit(values); }}><div className="template-grid"><div className="template-field"><label htmlFor="template-name">Template name</label><input id="template-name" name="name" value={values.name} onChange={update} required /></div><div className="template-field"><label htmlFor="template-channel">Channel</label><select id="template-channel" name="channel" value={values.channel} onChange={update}><option>Email</option><option>SMS</option><option>WhatsApp</option><option>Push notification</option></select></div><div className="template-field"><label htmlFor="template-subject">Subject</label><input id="template-subject" name="subject" value={values.subject} onChange={update} /></div><div className="template-field"><label htmlFor="template-body">Message body</label><textarea id="template-body" name="body" value={values.body} onChange={update} required /></div><div className="template-field"><label>Available variables</label><div className="template-variables">{['{{customerName}}','{{trackingNumber}}','{{deliveryDate}}','{{driverName}}'].map((variable) => <span key={variable} className="template-variable">{variable}</span>)}</div><span className="template-help">Use variables to personalize every notification.</span></div></div><div className="template-actions"><button type="button" className="template-cancel" onClick={onCancel}>Cancel</button><button type="submit" className="template-save">Save template</button></div></form></div>;
}
