import React, { useState } from 'react';
import { CheckCircle2 } from 'lucide-react';
import OTPInput from '../pod/OTPInput';
import SignaturePad from '../pod/SignaturePad';
import PhotoCapture from '../pod/PhotoCapture';

const styles = `.confirmation-form { display:grid; gap:20px; padding:20px; border:1px solid #E3E7EF; border-radius:14px; background:#fff; } .confirmation-section { padding-top:18px; border-top:1px solid #E3E7EF; } .confirmation-section:first-child { padding-top:0; border-top:0; } .confirmation-title { margin:0 0 5px; color:#12213F; font:700 15px 'Sora',sans-serif; } .confirmation-copy { margin:0 0 15px; color:#697086; font-size:12px; line-height:1.5; } .confirmation-label { display:block; margin-bottom:8px; color:#697086; font-size:12px; font-weight:700; } .confirmation-actions { display:flex; justify-content:flex-end; gap:10px; padding-top:18px; border-top:1px solid #E3E7EF; } .confirmation-button { padding:10px 15px; border:1px solid #E3E7EF; border-radius:9px; background:#fff; color:#12213F; font-size:12px; font-weight:700; cursor:pointer; } .confirmation-button.primary { border-color:#F5A524; background:#F5A524; color:#211200; } .confirmation-error { padding:10px 12px; border-radius:8px; background:#FDE9E7; color:#B23528; font-size:12px; font-weight:600; } .confirmation-success { display:flex; align-items:center; gap:7px; padding:10px 12px; border-radius:8px; background:#E4F7F4; color:#087367; font-size:12px; font-weight:700; }`;

export default function DeliveryConfirmationForm({ shipment = {}, onConfirm, onCancel }) {
	const [otp, setOtp] = useState(''); const [signature, setSignature] = useState(''); const [photo, setPhoto] = useState(null); const [error, setError] = useState(''); const [success, setSuccess] = useState(false);
	const submit = (event) => { event.preventDefault(); if (otp.length < 4 || !signature || !photo) { setError('Enter the customer OTP, capture a signature, and add a delivery photo.'); return; } setError(''); setSuccess(true); onConfirm?.({ shipmentId: shipment.id || '', otp, signature, photo }); };
	return <form className="confirmation-form" onSubmit={submit}><style>{styles}</style><div className="confirmation-section"><h2 className="confirmation-title">Confirm delivery</h2><p className="confirmation-copy">Complete all proof-of-delivery steps for {shipment.id || 'this shipment'}.</p><label className="confirmation-label">Customer OTP</label><OTPInput value={otp} onChange={setOtp} /></div><div className="confirmation-section"><label className="confirmation-label">Customer signature</label><SignaturePad onChange={setSignature} /></div><div className="confirmation-section"><label className="confirmation-label">Delivery photo</label><PhotoCapture onChange={setPhoto} /></div>{error && <div className="confirmation-error" role="alert">{error}</div>}{success && <div className="confirmation-success"><CheckCircle2 size={15} />Proof of delivery submitted.</div>}<div className="confirmation-actions"><button type="button" className="confirmation-button" onClick={onCancel}>Cancel</button><button type="submit" className="confirmation-button primary">Confirm delivery</button></div></form>;
}
