import React, { useState } from 'react';
import { Camera, Send } from 'lucide-react';

const styles = `.failed-form{padding:20px;border:1px solid #E3E7EF;border-radius:14px;background:#fff}.failed-form h2{margin:0 0 18px;color:#12213F;font:700 15px 'Sora',sans-serif}.failed-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.failed-field{display:grid;gap:7px}.failed-field.full{grid-column:1/-1}.failed-field label{color:#697086;font-size:11px;font-weight:700;letter-spacing:.04em;text-transform:uppercase}.failed-field input,.failed-field select,.failed-field textarea{width:100%;border:1px solid #E3E7EF;border-radius:10px;background:#F9FAFC;color:#12213F;padding:10px 12px;font-size:13px;outline:none}.failed-field textarea{min-height:90px;resize:vertical}.failed-field input:focus,.failed-field select:focus,.failed-field textarea:focus{border-color:#EF5B4E;box-shadow:0 0 0 3px rgba(239,91,78,.12)}.failed-photo{display:flex;align-items:center;gap:7px;color:#697086;font-size:11.5px}.failed-actions{display:flex;justify-content:flex-end;gap:10px;margin-top:18px}.failed-actions button{border:1px solid #E3E7EF;border-radius:10px;padding:10px 14px;font-size:12px;font-weight:700;cursor:pointer}.failed-cancel{background:#fff;color:#12213F}.failed-submit{background:#EF5B4E;color:#fff;border-color:#EF5B4E!important}@media(max-width:560px){.failed-grid{grid-template-columns:1fr}.failed-field.full{grid-column:auto}}`;
const defaults = { shipment: 'SH-28495', reason: 'Recipient unavailable', attempt: '2', nextAttempt: '2026-09-09', notes: '' };

export default function FailedDeliveryForm({ initialValues = defaults, onSubmit = () => {}, onCancel = () => {} }) {
	const [values, setValues] = useState({ ...defaults, ...initialValues });
	const update = (event) => setValues((current) => ({ ...current, [event.target.name]: event.target.value }));
	return <div className="failed-form"><style>{styles}</style><h2>Record failed delivery</h2><form onSubmit={(event) => { event.preventDefault(); onSubmit(values); }}><div className="failed-grid"><div className="failed-field"><label htmlFor="failed-shipment">Shipment number</label><input id="failed-shipment" name="shipment" value={values.shipment} onChange={update} required /></div><div className="failed-field"><label htmlFor="failed-attempt">Delivery attempt</label><select id="failed-attempt" name="attempt" value={values.attempt} onChange={update}><option>1</option><option>2</option><option>3</option></select></div><div className="failed-field"><label htmlFor="failed-reason">Failure reason</label><select id="failed-reason" name="reason" value={values.reason} onChange={update}><option>Recipient unavailable</option><option>Incorrect address</option><option>Refused by recipient</option><option>Access issue</option><option>Damaged at delivery</option></select></div><div className="failed-field"><label htmlFor="failed-next">Next attempt date</label><input id="failed-next" name="nextAttempt" type="date" value={values.nextAttempt} onChange={update} /></div><div className="failed-field full"><label htmlFor="failed-notes">Notes</label><textarea id="failed-notes" name="notes" value={values.notes} onChange={update} placeholder="Add delivery notes or recipient instructions" /></div><label className="failed-photo"><Camera size={14}/> Attach attempt photo <input type="file" accept="image/*" hidden /></label></div><div className="failed-actions"><button type="button" className="failed-cancel" onClick={onCancel}>Cancel</button><button type="submit" className="failed-submit"><Send size={14}/> Save attempt</button></div></form></div>;
}
