import React, { useState } from 'react';

const styles = `.pricing-form{padding:20px;border:1px solid #E3E7EF;border-radius:14px;background:#fff}.pricing-form h2{margin:0 0 18px;color:#12213F;font:700 15px 'Sora',sans-serif}.pricing-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.pricing-field{display:grid;gap:7px}.pricing-field.full{grid-column:1/-1}.pricing-field label{color:#697086;font-size:11px;font-weight:700;letter-spacing:.04em;text-transform:uppercase}.pricing-field input,.pricing-field select{width:100%;border:1px solid #E3E7EF;border-radius:10px;background:#F9FAFC;color:#12213F;padding:10px 12px;font-size:13px;outline:none}.pricing-field input:focus,.pricing-field select:focus{border-color:#3E7BFA;box-shadow:0 0 0 3px rgba(62,123,250,.12)}.pricing-actions{display:flex;justify-content:flex-end;gap:10px;margin-top:18px}.pricing-actions button{border:1px solid #E3E7EF;border-radius:10px;padding:10px 14px;font-size:12px;font-weight:700;cursor:pointer}.pricing-cancel{background:#fff;color:#12213F}.pricing-save{background:#12213F;color:#fff;border-color:#12213F!important}@media(max-width:560px){.pricing-grid{grid-template-columns:1fr}.pricing-field.full{grid-column:auto}}`;
const defaults = { name: 'Standard domestic', service: 'Standard', zone: 'Domestic', basePrice: '450', perKg: '85', codFee: '1.5', status: 'Active' };

export default function PricingRuleForm({ initialValues = defaults, onSubmit = () => {}, onCancel = () => {} }) {
	const [values, setValues] = useState({ ...defaults, ...initialValues });
	const update = (event) => setValues((current) => ({ ...current, [event.target.name]: event.target.value }));
	return <div className="pricing-form"><style>{styles}</style><h2>Pricing rule</h2><form onSubmit={(event) => { event.preventDefault(); onSubmit(values); }}><div className="pricing-grid"><div className="pricing-field full"><label htmlFor="pricing-name">Rule name</label><input id="pricing-name" name="name" value={values.name} onChange={update} required /></div><div className="pricing-field"><label htmlFor="pricing-service">Service</label><select id="pricing-service" name="service" value={values.service} onChange={update}><option>Standard</option><option>Same-day</option><option>Express</option><option>Returns</option></select></div><div className="pricing-field"><label htmlFor="pricing-zone">Zone</label><select id="pricing-zone" name="zone" value={values.zone} onChange={update}><option>Domestic</option><option>Metro</option><option>Regional</option><option>Islandwide</option></select></div><div className="pricing-field"><label htmlFor="pricing-base">Base price (LKR)</label><input id="pricing-base" name="basePrice" type="number" min="0" value={values.basePrice} onChange={update} /></div><div className="pricing-field"><label htmlFor="pricing-kg">Price per kg</label><input id="pricing-kg" name="perKg" type="number" min="0" value={values.perKg} onChange={update} /></div><div className="pricing-field"><label htmlFor="pricing-cod">COD fee (%)</label><input id="pricing-cod" name="codFee" type="number" min="0" step="0.1" value={values.codFee} onChange={update} /></div><div className="pricing-field"><label htmlFor="pricing-status">Status</label><select id="pricing-status" name="status" value={values.status} onChange={update}><option>Active</option><option>Draft</option><option>Archived</option></select></div></div><div className="pricing-actions"><button type="button" className="pricing-cancel" onClick={onCancel}>Cancel</button><button type="submit" className="pricing-save">Save rule</button></div></form></div>;
}
