import React, { useState } from 'react';
import { CheckCircle2, MapPin, Search, XCircle } from 'lucide-react';

const styles = `.serviceability{padding:20px;border:1px solid #E3E7EF;border-radius:14px;background:#fff}.serviceability h2{margin:0 0 6px;color:#12213F;font:700 15px 'Sora',sans-serif}.serviceability-copy{margin:0 0 16px;color:#697086;font-size:12px}.serviceability-form{display:flex;gap:8px}.serviceability-form input{min-width:0;flex:1;border:1px solid #E3E7EF;border-radius:10px;background:#F9FAFC;color:#12213F;padding:10px 12px;font-size:13px;outline:none}.serviceability-form button{display:inline-flex;align-items:center;gap:7px;border:1px solid #12213F;border-radius:10px;padding:10px 13px;background:#12213F;color:#fff;font-size:12px;font-weight:700;cursor:pointer}.service-result{display:flex;align-items:flex-start;gap:9px;margin-top:16px;padding:12px;border-radius:10px;font-size:12px;font-weight:600}.service-result.available{background:#E4F7F4;color:#087367}.service-result.unavailable{background:#FDE9E7;color:#B23528}@media(max-width:500px){.serviceability-form{flex-direction:column}.serviceability-form button{justify-content:center}}`;

export default function ServiceabilityChecker({ onCheck = () => {} }) {
	const [postalCode, setPostalCode] = useState('00100');
	const [result, setResult] = useState(null);
	const check = (event) => { event.preventDefault(); const available = /^0(0|1|2|3|4|5|6|7|8|9)/.test(postalCode.trim()); const value = { postalCode: postalCode.trim(), available, zone: available ? 'Colombo Metro' : null }; setResult(value); onCheck(value); };
	return <div className="serviceability"><style>{styles}</style><h2>Check serviceability</h2><p className="serviceability-copy">Confirm whether a postal code is covered by the current delivery network.</p><form className="serviceability-form" onSubmit={check}><input aria-label="Postal code" value={postalCode} onChange={(event) => setPostalCode(event.target.value)} placeholder="Enter postal code" /><button type="submit"><Search size={14} /> Check</button></form>{result ? <div className={`service-result ${result.available ? 'available' : 'unavailable'}`}>{result.available ? <CheckCircle2 size={16} /> : <XCircle size={16} />}<span>{result.available ? `${result.postalCode} is serviceable through ${result.zone}.` : `${result.postalCode} is not currently serviceable.`}</span>{result.available ? <MapPin size={14} /> : null}</div> : null}</div>;
}
