import React, { useState } from 'react';

const styles = `.zone-form{padding:20px;border:1px solid #E3E7EF;border-radius:14px;background:#fff}.zone-form h2{margin:0 0 18px;color:#12213F;font:700 15px 'Sora',sans-serif}.zone-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.zone-field{display:grid;gap:7px}.zone-field.full{grid-column:1/-1}.zone-field label{color:#697086;font-size:11px;font-weight:700;letter-spacing:.04em;text-transform:uppercase}.zone-field input,.zone-field select,.zone-field textarea{width:100%;border:1px solid #E3E7EF;border-radius:10px;background:#F9FAFC;color:#12213F;padding:10px 12px;font-size:13px;outline:none}.zone-field textarea{min-height:70px;resize:vertical}.zone-field input:focus,.zone-field select:focus,.zone-field textarea:focus{border-color:#3E7BFA;box-shadow:0 0 0 3px rgba(62,123,250,.12)}.zone-actions{display:flex;justify-content:flex-end;gap:10px;margin-top:18px}.zone-actions button{border:1px solid #E3E7EF;border-radius:10px;padding:10px 14px;font-size:12px;font-weight:700;cursor:pointer}.zone-cancel{background:#fff;color:#12213F}.zone-save{background:#12213F;color:#fff;border-color:#12213F!important}@media(max-width:560px){.zone-grid{grid-template-columns:1fr}.zone-field.full{grid-column:auto}}`;
const defaults = { name: 'Colombo Metro', code: 'COL-MET', type: 'Metro', postalCodes: '00100, 00200, 00300', surcharge: '0', status: 'Active' };

export default function ZoneForm({ initialValues = defaults, onSubmit = () => {}, onCancel = () => {} }) {
	const [values, setValues] = useState({ ...defaults, ...initialValues });
	const update = (event) => setValues((current) => ({ ...current, [event.target.name]: event.target.value }));
	return <div className="zone-form"><style>{styles}</style><h2>Service zone</h2><form onSubmit={(event) => { event.preventDefault(); onSubmit(values); }}><div className="zone-grid"><div className="zone-field"><label htmlFor="zone-name">Zone name</label><input id="zone-name" name="name" value={values.name} onChange={update} required /></div><div className="zone-field"><label htmlFor="zone-code">Zone code</label><input id="zone-code" name="code" value={values.code} onChange={update} required /></div><div className="zone-field"><label htmlFor="zone-type">Zone type</label><select id="zone-type" name="type" value={values.type} onChange={update}><option>Metro</option><option>Regional</option><option>Remote</option><option>Islandwide</option></select></div><div className="zone-field"><label htmlFor="zone-surcharge">Surcharge (LKR)</label><input id="zone-surcharge" name="surcharge" type="number" min="0" value={values.surcharge} onChange={update} /></div><div className="zone-field full"><label htmlFor="zone-postal">Postal codes</label><textarea id="zone-postal" name="postalCodes" value={values.postalCodes} onChange={update} placeholder="Comma-separated postal codes" /></div><div className="zone-field"><label htmlFor="zone-status">Status</label><select id="zone-status" name="status" value={values.status} onChange={update}><option>Active</option><option>Draft</option><option>Paused</option></select></div></div><div className="zone-actions"><button type="button" className="zone-cancel" onClick={onCancel}>Cancel</button><button type="submit" className="zone-save">Save zone</button></div></form></div>;
}
