import React, { useMemo, useState } from 'react';
import { ArrowRight, Check, Package, Save } from 'lucide-react';
import { MerchantButton, MerchantCard, MerchantShell } from './MerchantShell';

export default function CreateShipmentPage() {
  const [created, setCreated] = useState(false);
  const [service, setService] = useState('Standard');
  const [weight, setWeight] = useState('1');
  const base = useMemo(() => { const kg = Number(weight) || 0; return kg <= 1 ? 350 : kg <= 2 ? 450 : kg <= 5 ? 650 : 900; }, [weight]);
  if (created) return <MerchantShell title="Create shipment" subtitle="Your shipment is ready for pickup."><MerchantCard><div style={{ maxWidth: 520, margin: '45px auto', textAlign: 'center' }}><div className="merchant-success-icon"><Check size={30} /></div><span className="merchant-eyebrow">Shipment created</span><h2 style={{ margin: '8px 0', fontFamily: 'Sora', color: '#12213f' }}>EGW-2026-00001252</h2><p style={{ color: '#697086', fontSize: 12, lineHeight: 1.6 }}>Your waybill is ready. We will confirm the pickup window by SMS and email.</p><MerchantButton to="/merchant/shipments">Track shipment <ArrowRight size={15} /></MerchantButton></div></MerchantCard></MerchantShell>;
  return <MerchantShell title="Create shipment" subtitle="Book a new delivery for your customers." action={<MerchantButton secondary><Save size={15} /> Save draft</MerchantButton>}><form onSubmit={(event) => { event.preventDefault(); setCreated(true); }}><MerchantCard><Section title="Recipient details" icon={Package}><div className="merchant-form-grid"><Field label="Recipient name" placeholder="John Perera" required /><Field label="Phone number" placeholder="077 123 4567" required /><Field label="Delivery address" placeholder="House number, street and area" required full /><Field label="City / district" value="Kandy" /><Field label="Delivery instructions" placeholder="Landmark or driver notes" /></div></Section><MerchantCard className="form-section"><Section title="Package and service" icon={Package}><div className="merchant-form-grid"><Field label="Package description" placeholder="Electronics" required /><Field label="Weight (kg)" type="number" value={weight} onChange={(event) => setWeight(event.target.value)} required /><label className="merchant-field"><span>Delivery service</span><select value={service} onChange={(event) => setService(event.target.value)}><option>Standard</option><option>Express</option><option>Priority</option></select></label><Field label="COD amount (Rs)" placeholder="4500" type="number" /><Field label="Pickup date" type="date" value="2026-09-09" /></div></Section></MerchantCard><div className="merchant-form-actions"><MerchantButton secondary to="/merchant">Cancel</MerchantButton><MerchantButton type="submit">Review and create <ArrowRight size={15} /></MerchantButton></div></MerchantCard></form><aside style={{ marginTop: 15, padding: 13, borderRadius: 8, background: '#e4f7f4', color: '#087367', fontSize: 10.5 }}>Estimated delivery charge: <strong>Rs {base + (service === 'Express' ? 250 : service === 'Priority' ? 450 : 0)}</strong>. Final pricing is confirmed by the server from your rate card.</aside></MerchantShell>;
}
function Section({ title, icon: Icon, children }) { return <div><div className="merchant-card-heading"><div><span className="merchant-eyebrow">Shipment section</span><h2>{title}</h2></div><Icon size={18} color="#3e7bfa" /></div>{children}</div>; }
function Field({ label, full, ...props }) { return <label className={`merchant-field ${full ? 'full' : ''}`}><span>{label}</span><input {...props} /></label>; }
