import React, { useEffect } from 'react';
import { X } from 'lucide-react';

const styles = `.common-modal-backdrop{position:fixed;z-index:1000;inset:0;display:flex;align-items:center;justify-content:center;padding:20px;background:rgba(18,33,63,.48)}.common-modal{width:100%;max-width:560px;max-height:min(720px,calc(100vh - 40px));overflow:auto;border:1px solid #E3E7EF;border-radius:14px;background:#fff;box-shadow:0 18px 48px rgba(18,33,63,.2)}.common-modal-header{display:flex;align-items:flex-start;justify-content:space-between;gap:12px;padding:20px;border-bottom:1px solid #E3E7EF}.common-modal-title{margin:0;color:#12213F;font:700 16px 'Sora',sans-serif}.common-modal-description{margin:5px 0 0;color:#697086;font-size:12px}.common-modal-close{display:grid;place-items:center;width:30px;height:30px;border:0;border-radius:8px;background:#F3F5F9;color:#697086;cursor:pointer}.common-modal-body{padding:20px}.common-modal-footer{display:flex;justify-content:flex-end;gap:9px;padding:0 20px 20px}@media(max-width:520px){.common-modal-backdrop{padding:12px}.common-modal-header,.common-modal-body{padding:16px}.common-modal-footer{padding:0 16px 16px}}`;

export default function Modal({ open = false, onClose = () => {}, title, description, children, footer, closeOnBackdrop = true, className = '' }) {
	useEffect(() => { if (!open) return undefined; const handleKey = (event) => { if (event.key === 'Escape') onClose(); }; document.addEventListener('keydown', handleKey); return () => document.removeEventListener('keydown', handleKey); }, [open, onClose]);
	if (!open) return null;
	return <div className="common-modal-backdrop" role="presentation" onMouseDown={(event) => { if (closeOnBackdrop && event.target === event.currentTarget) onClose(); }}><style>{styles}</style><div className={`common-modal ${className}`.trim()} role="dialog" aria-modal="true" aria-labelledby={title ? 'common-modal-title' : undefined}><header className="common-modal-header"><div>{title ? <h2 id="common-modal-title" className="common-modal-title">{title}</h2> : null}{description ? <p className="common-modal-description">{description}</p> : null}</div><button type="button" className="common-modal-close" onClick={onClose} aria-label="Close dialog"><X size={16} /></button></header><div className="common-modal-body">{children}</div>{footer ? <footer className="common-modal-footer">{footer}</footer> : null}</div></div>;
}
