import React, { useState } from 'react';
import { Send } from 'lucide-react';

const styles = `.complaint-form{padding:20px;border:1px solid #E3E7EF;border-radius:14px;background:#fff}.complaint-form h2{margin:0 0 18px;color:#12213F;font:700 15px 'Sora',sans-serif}.complaint-grid{display:grid;gap:14px}.complaint-field{display:grid;gap:7px}.complaint-field label{color:#697086;font-size:11px;font-weight:700;letter-spacing:.04em;text-transform:uppercase}.complaint-field input,.complaint-field select,.complaint-field textarea{width:100%;border:1px solid #E3E7EF;border-radius:10px;background:#F9FAFC;color:#12213F;padding:10px 12px;font-size:13px;outline:none}.complaint-field textarea{min-height:110px;resize:vertical}.complaint-field input:focus,.complaint-field select:focus,.complaint-field textarea:focus{border-color:#3E7BFA;box-shadow:0 0 0 3px rgba(62,123,250,.12)}.complaint-actions{display:flex;justify-content:flex-end;gap:10px;margin-top:18px}.complaint-actions button{display:inline-flex;align-items:center;gap:7px;border:1px solid #E3E7EF;border-radius:10px;padding:10px 14px;font-size:12px;font-weight:700;cursor:pointer}.complaint-cancel{background:#fff;color:#12213F}.complaint-submit{background:#12213F;color:#fff;border-color:#12213F!important}`;
const defaults = { shipment: '', type: 'Late delivery', severity: 'Medium', description: '' };

export default function ComplaintForm({ initialValues = defaults, onSubmit = () => {}, onCancel = () => {} }) {
	const [values, setValues] = useState({ ...defaults, ...initialValues });
	const update = (event) => setValues((current) => ({ ...current, [event.target.name]: event.target.value }));
	return <div className="complaint-form"><style>{styles}</style><h2>Register a complaint</h2><form onSubmit={(event) => { event.preventDefault(); onSubmit(values); }}><div className="complaint-grid"><div className="complaint-field"><label htmlFor="complaint-shipment">Shipment number</label><input id="complaint-shipment" name="shipment" value={values.shipment} onChange={update} placeholder="SH-28491" required /></div><div className="complaint-field"><label htmlFor="complaint-type">Complaint type</label><select id="complaint-type" name="type" value={values.type} onChange={update}><option>Late delivery</option><option>Damaged parcel</option><option>Missing parcel</option><option>Wrong item</option><option>Driver conduct</option></select></div><div className="complaint-field"><label htmlFor="complaint-severity">Severity</label><select id="complaint-severity" name="severity" value={values.severity} onChange={update}><option>Low</option><option>Medium</option><option>High</option><option>Critical</option></select></div><div className="complaint-field"><label htmlFor="complaint-description">Details</label><textarea id="complaint-description" name="description" value={values.description} onChange={update} placeholder="Describe the complaint" required /></div></div><div className="complaint-actions"><button type="button" className="complaint-cancel" onClick={onCancel}>Cancel</button><button type="submit" className="complaint-submit"><Send size={14} /> Submit complaint</button></div></form></div>;
}
