import React, { useState } from 'react';
import { Send } from 'lucide-react';

const styles = `.ticket-thread{padding:20px;border:1px solid #E3E7EF;border-radius:14px;background:#fff}.thread-head{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:16px}.thread-title{margin:0;color:#12213F;font:700 15px 'Sora',sans-serif}.thread-status{padding:5px 9px;border-radius:999px;background:#FCEFD6;color:#8A5A05;font-size:11px;font-weight:700}.thread-list{display:grid;gap:14px}.thread-message{display:flex;gap:10px}.thread-message.own{flex-direction:row-reverse}.thread-avatar{width:30px;height:30px;display:grid;place-items:center;flex-shrink:0;border-radius:9px;background:#E8EFFE;color:#2453B8;font-size:11px;font-weight:800}.thread-message.own .thread-avatar{background:#E4F7F4;color:#087367}.thread-bubble{max-width:78%;padding:11px 13px;border-radius:11px;background:#F3F5F9;color:#12213F;font-size:12.5px;line-height:1.45}.thread-message.own .thread-bubble{background:#E8EFFE}.thread-meta{margin-top:5px;color:#9AA1B4;font-size:10.5px}.thread-reply{display:flex;gap:8px;margin-top:18px;padding-top:16px;border-top:1px solid #E3E7EF}.thread-reply textarea{min-height:42px;flex:1;border:1px solid #E3E7EF;border-radius:10px;padding:10px 12px;resize:vertical;font-size:12px;outline:none}.thread-reply textarea:focus{border-color:#3E7BFA}.thread-reply button{align-self:flex-end;display:grid;place-items:center;width:38px;height:38px;border:0;border-radius:10px;background:#12213F;color:#fff;cursor:pointer}`;
const defaults = [{ id: 1, author: 'Support team', initials: 'ST', text: 'Thanks for reaching out. We are checking the latest scan from the Kandy hub.', time: 'Today, 10:14 AM', own: false }, { id: 2, author: 'Nayani Rathnayake', initials: 'NR', text: 'Thank you. The recipient has still not received an updated delivery time.', time: 'Today, 10:26 AM', own: true }];

export default function TicketThread({ messages = defaults, onReply = () => {} }) {
	const [reply, setReply] = useState('');
	const submit = (event) => { event.preventDefault(); if (!reply.trim()) return; onReply(reply.trim()); setReply(''); };
	return <div className="ticket-thread"><style>{styles}</style><div className="thread-head"><h2 className="thread-title">Conversation</h2><span className="thread-status">Waiting for reply</span></div><div className="thread-list">{messages.map((message) => <div className={`thread-message ${message.own ? 'own' : ''}`} key={message.id}><div className="thread-avatar">{message.initials}</div><div><div className="thread-bubble">{message.text}</div><div className="thread-meta">{message.author} · {message.time}</div></div></div>)}</div><form className="thread-reply" onSubmit={submit}><textarea value={reply} onChange={(event) => setReply(event.target.value)} placeholder="Write a reply..." aria-label="Reply" /><button type="submit" aria-label="Send reply"><Send size={15} /></button></form></div>;
}
