import React, { useState } from 'react';
import { Paperclip, Send } from 'lucide-react';

const styles = `.ticket-form{padding:20px;border:1px solid #E3E7EF;border-radius:14px;background:#fff}.ticket-form h2{margin:0 0 18px;color:#12213F;font:700 15px 'Sora',sans-serif}.ticket-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.ticket-field{display:grid;gap:7px}.ticket-field.full{grid-column:1/-1}.ticket-field label{color:#697086;font-size:11px;font-weight:700;letter-spacing:.04em;text-transform:uppercase}.ticket-field input,.ticket-field select,.ticket-field textarea{width:100%;border:1px solid #E3E7EF;border-radius:10px;background:#F9FAFC;color:#12213F;padding:10px 12px;font-size:13px;outline:none}.ticket-field textarea{min-height:110px;resize:vertical}.ticket-field input:focus,.ticket-field select:focus,.ticket-field textarea:focus{border-color:#3E7BFA;box-shadow:0 0 0 3px rgba(62,123,250,.12)}.ticket-attachment{display:flex;align-items:center;gap:7px;color:#697086;font-size:11.5px}.ticket-actions{display:flex;justify-content:flex-end;gap:10px;margin-top:18px}.ticket-actions button{display:inline-flex;align-items:center;gap:7px;border:1px solid #E3E7EF;border-radius:10px;padding:10px 14px;font-size:12px;font-weight:700;cursor:pointer}.ticket-cancel{background:#fff;color:#12213F}.ticket-submit{background:#12213F;color:#fff;border-color:#12213F!important}@media(max-width:560px){.ticket-grid{grid-template-columns:1fr}.ticket-field.full{grid-column:auto}}`;
const defaults = { subject: '', category: 'Shipment', priority: 'Normal', relatedShipment: '', description: '' };

export default function TicketForm({ initialValues = defaults, onSubmit = () => {}, onCancel = () => {} }) {
	const [values, setValues] = useState({ ...defaults, ...initialValues });
	const update = (event) => setValues((current) => ({ ...current, [event.target.name]: event.target.value }));
	return <div className="ticket-form"><style>{styles}</style><h2>Open a support ticket</h2><form onSubmit={(event) => { event.preventDefault(); onSubmit(values); }}><div className="ticket-grid"><div className="ticket-field full"><label htmlFor="ticket-subject">Subject</label><input id="ticket-subject" name="subject" value={values.subject} onChange={update} placeholder="Briefly describe the issue" required /></div><div className="ticket-field"><label htmlFor="ticket-category">Category</label><select id="ticket-category" name="category" value={values.category} onChange={update}><option>Shipment</option><option>Payment</option><option>Account</option><option>Technical</option><option>General</option></select></div><div className="ticket-field"><label htmlFor="ticket-priority">Priority</label><select id="ticket-priority" name="priority" value={values.priority} onChange={update}><option>Low</option><option>Normal</option><option>High</option><option>Urgent</option></select></div><div className="ticket-field full"><label htmlFor="ticket-shipment">Related shipment</label><input id="ticket-shipment" name="relatedShipment" value={values.relatedShipment} onChange={update} placeholder="Optional tracking number" /></div><div className="ticket-field full"><label htmlFor="ticket-description">Description</label><textarea id="ticket-description" name="description" value={values.description} onChange={update} placeholder="Tell us what happened and how we can help" required /></div><label className="ticket-attachment"><Paperclip size={14} /> Attach supporting files <input type="file" hidden /></label></div><div className="ticket-actions"><button type="button" className="ticket-cancel" onClick={onCancel}>Cancel</button><button type="submit" className="ticket-submit"><Send size={14} /> Submit ticket</button></div></form></div>;
}
