import React from 'react';
import { Building2, CheckCircle2, MapPin, PackageCheck } from 'lucide-react';
import PortalLayout from '../../components/layout/PortalLayout';
import KpiDashboard from '../../components/reports/KpiDashboard';
import ReportChart from '../../components/reports/ReportChart';
import ExportButton from '../../components/common/ExportButton';

const styles = `.report-page { display:grid; gap:20px; padding:24px; } .report-head { display:flex; align-items:flex-end; justify-content:space-between; gap:16px; } .eyebrow { margin:0 0 5px; color:#9AA1B4; font-size:12px; font-weight:700; letter-spacing:.08em; text-transform:uppercase; } .report-title { margin:0; color:#12213F; font:700 22px 'Sora',sans-serif; } .report-subtitle { margin:8px 0 0; color:#697086; font-size:13px; } .report-actions { display:flex; align-items:center; gap:9px; } .range-select { border:1px solid #E3E7EF; border-radius:10px; padding:10px 12px; background:#fff; color:#12213F; font-size:12px; } .report-grid { display:grid; grid-template-columns:1.2fr .8fr; gap:16px; } .report-panel { border:1px solid #E3E7EF; border-radius:14px; padding:18px 20px; background:#fff; } .panel-title { margin:0 0 14px; color:#12213F; font:700 14.5px 'Sora',sans-serif; } table { width:100%; border-collapse:collapse; } th { padding:0 10px 10px; color:#9AA1B4; font-size:11px; text-align:left; text-transform:uppercase; } td { padding:12px 10px; border-top:1px solid #E3E7EF; color:#12213F; font-size:12.5px; } .good { color:#0C8C6B; font-weight:700; } .muted { margin-top:3px; color:#697086; font-size:11px; } @media(max-width:850px){.report-page{padding:16px}.report-head{align-items:flex-start;flex-direction:column}.report-grid{grid-template-columns:1fr}}`;
const metrics = [{ label: 'Active branches', value: '18', delta: '4 regional hubs', icon: Building2 }, { label: 'Branch shipments', value: '8,642', delta: '+12.8% vs last period', icon: PackageCheck, iconBg: '#E8EFFE', iconColor: '#2453B8' }, { label: 'Network on-time rate', value: '96.8%', delta: '+2.1% improvement', icon: CheckCircle2, iconBg: '#E4F7F4', iconColor: '#0C8C6B' }, { label: 'Coverage zones', value: '42', delta: 'All serviceable', icon: MapPin, iconBg: '#FCEFD6', iconColor: '#8A5A05' }];
export default function BranchReportsPage() { return <PortalLayout><div className="report-page"><style>{styles}</style><div className="report-head"><div><p className="eyebrow">Reports / Branches</p><h1 className="report-title">Branch performance</h1><p className="report-subtitle">Compare branch throughput, service reliability, and network coverage.</p></div><div className="report-actions"><select className="range-select" defaultValue="30"><option value="30">Last 30 days</option><option value="90">Last 90 days</option></select><ExportButton /></div></div><KpiDashboard metrics={metrics} /><div className="report-grid"><ReportChart title="Branch throughput" meta="Daily parcels" data={[520,640,590,720,680,780,742]} labels={['Mon','Tue','Wed','Thu','Fri','Sat','Sun']} color="#F5A524" /><div className="report-panel"><h2 className="panel-title">Branch ranking</h2><table><thead><tr><th>Branch</th><th>Shipments</th><th>On-time</th></tr></thead><tbody>{[['Colombo Central','3,420','98.1%'],['Kandy Operations','2,180','95.4%'],['Galle South','1,884','96.2%'],['Negombo Regional','1,158','94.8%']].map((row) => <tr key={row[0]}><td><div>{row[0]}</div><div className="muted">Regional operation</div></td><td>{row[1]}</td><td className="good">{row[2]}</td></tr>)}</tbody></table></div></div><div className="report-panel"><h2 className="panel-title">Capacity utilization</h2><table><thead><tr><th>Branch</th><th>Daily capacity</th><th>Utilization</th><th>Available</th></tr></thead><tbody>{[['Colombo Central','4,200','78%','924'],['Kandy Operations','2,100','64%','756'],['Galle South','1,500','51%','735'],['Negombo Regional','1,200','31%','828']].map((row) => <tr key={row[0]}>{row.map((value, index) => <td key={value} className={index === 2 ? 'good' : ''}>{value}</td>)}</tr>)}</tbody></table></div></div></PortalLayout>; }
