import React from 'react';
import { Award, CheckCircle2, Clock3, Truck } from 'lucide-react';
import PortalLayout from '../../components/layout/PortalLayout';
import KpiDashboard from '../../components/reports/KpiDashboard';
import ReportChart from '../../components/reports/ReportChart';
import ExportButton from '../../components/common/ExportButton';

const styles = `.report-page { display:grid; gap:20px; padding:24px; } .report-head { display:flex; align-items:flex-end; justify-content:space-between; gap:16px; } .eyebrow { margin:0 0 5px; color:#9AA1B4; font-size:12px; font-weight:700; letter-spacing:.08em; text-transform:uppercase; } .report-title { margin:0; color:#12213F; font:700 22px 'Sora',sans-serif; } .report-subtitle { margin:8px 0 0; color:#697086; font-size:13px; } .report-actions { display:flex; align-items:center; gap:9px; } .range-select { border:1px solid #E3E7EF; border-radius:10px; padding:10px 12px; background:#fff; color:#12213F; font-size:12px; } .report-grid { display:grid; grid-template-columns:1.2fr .8fr; gap:16px; } .report-panel { border:1px solid #E3E7EF; border-radius:14px; padding:18px 20px; background:#fff; } .panel-title { margin:0 0 14px; color:#12213F; font:700 14.5px 'Sora',sans-serif; } table { width:100%; border-collapse:collapse; } th { padding:0 10px 10px; color:#9AA1B4; font-size:11px; text-align:left; text-transform:uppercase; } td { padding:12px 10px; border-top:1px solid #E3E7EF; color:#12213F; font-size:12.5px; } .good { color:#0C8C6B; font-weight:700; } .muted { margin-top:3px; color:#697086; font-size:11px; } @media(max-width:850px){.report-page{padding:16px}.report-head{align-items:flex-start;flex-direction:column}.report-grid{grid-template-columns:1fr}}`;
const metrics = [{ label: 'Active drivers', value: '148', delta: '+9 this period', icon: Truck }, { label: 'Deliveries completed', value: '7,842', delta: '+14.2% vs last period', icon: CheckCircle2, iconBg: '#E4F7F4', iconColor: '#0C8C6B' }, { label: 'Driver on-time rate', value: '95.6%', delta: '+1.8% improvement', icon: Clock3, iconBg: '#FCEFD6', iconColor: '#8A5A05' }, { label: 'Top performer score', value: '4.92', delta: 'Ravindu Silva', icon: Award, iconBg: '#EEECFE', iconColor: '#5445D6' }];
export default function DriverReportsPage() { return <PortalLayout><div className="report-page"><style>{styles}</style><div className="report-head"><div><p className="eyebrow">Reports / Drivers</p><h1 className="report-title">Driver performance</h1><p className="report-subtitle">Compare driver productivity, reliability, and service quality across routes.</p></div><div className="report-actions"><select className="range-select" defaultValue="30"><option value="30">Last 30 days</option><option value="90">Last 90 days</option></select><ExportButton /></div></div><KpiDashboard metrics={metrics} /><div className="report-grid"><ReportChart title="Completed deliveries" meta="Daily completions" data={[820, 960, 910, 1040, 980, 1140, 1080]} labels={['Mon','Tue','Wed','Thu','Fri','Sat','Sun']} color="#0EA394" /><div className="report-panel"><h2 className="panel-title">Leaderboard</h2><table><thead><tr><th>Driver</th><th>Deliveries</th><th>Score</th></tr></thead><tbody>{[['Ravindu Silva','184','4.92'],['Nimali Fernando','176','4.88'],['Kasun Perera','168','4.84'],['Sahan Wickram','161','4.79']].map((row) => <tr key={row[0]}><td><div>{row[0]}</div><div className="muted">Route specialist</div></td><td>{row[1]}</td><td className="good">{row[2]}</td></tr>)}</tbody></table></div></div><div className="report-panel"><h2 className="panel-title">Driver status summary</h2><table><thead><tr><th>Status</th><th>Drivers</th><th>Utilization</th><th>Avg. stops</th></tr></thead><tbody>{[['On route','76','51.4%','24'],['Available','48','32.4%','18'],['Break','15','10.1%','16'],['Offline','9','6.1%','12']].map((row) => <tr key={row[0]}>{row.map((value, index) => <td key={value} className={index === 2 ? 'good' : ''}>{value}</td>)}</tr>)}</tbody></table></div></div></PortalLayout>; }
