import React from 'react';
import { CheckCircle2, CreditCard, TrendingUp, WalletCards } from 'lucide-react';
import PortalLayout from '../../components/layout/PortalLayout';
import KpiDashboard from '../../components/reports/KpiDashboard';
import ReportChart from '../../components/reports/ReportChart';
import ExportButton from '../../components/common/ExportButton';

const styles = `.report-page { display:grid; gap:20px; padding:24px; } .report-head { display:flex; align-items:flex-end; justify-content:space-between; gap:16px; } .eyebrow { margin:0 0 5px; color:#9AA1B4; font-size:12px; font-weight:700; letter-spacing:.08em; text-transform:uppercase; } .report-title { margin:0; color:#12213F; font:700 22px 'Sora',sans-serif; } .report-subtitle { margin:8px 0 0; color:#697086; font-size:13px; } .report-actions { display:flex; align-items:center; gap:9px; } .range-select { border:1px solid #E3E7EF; border-radius:10px; padding:10px 12px; background:#fff; color:#12213F; font-size:12px; } .report-grid { display:grid; grid-template-columns:1.2fr .8fr; gap:16px; } .report-panel { border:1px solid #E3E7EF; border-radius:14px; padding:18px 20px; background:#fff; } .panel-title { margin:0 0 14px; color:#12213F; font:700 14.5px 'Sora',sans-serif; } table { width:100%; border-collapse:collapse; } th { padding:0 10px 10px; color:#9AA1B4; font-size:11px; text-align:left; text-transform:uppercase; } td { padding:12px 10px; border-top:1px solid #E3E7EF; color:#12213F; font-size:12.5px; } .good { color:#0C8C6B; font-weight:700; } .muted { margin-top:3px; color:#697086; font-size:11px; } @media(max-width:850px){.report-page{padding:16px}.report-head{align-items:flex-start;flex-direction:column}.report-grid{grid-template-columns:1fr}}`;
const metrics = [{ label: 'Gross revenue', value: 'Rs 18.6M', delta: '+14.2% vs last period', icon: TrendingUp }, { label: 'COD collected', value: 'Rs 8.4M', delta: '+9.8% this month', icon: WalletCards, iconBg: '#E4F7F4', iconColor: '#0C8C6B' }, { label: 'Pending settlement', value: 'Rs 1.2M', delta: '4.6% of revenue', positive: false, icon: CreditCard, iconBg: '#FCEFD6', iconColor: '#8A5A05' }, { label: 'Collection rate', value: '98.4%', delta: '+0.8% improvement', icon: CheckCircle2, iconBg: '#EEECFE', iconColor: '#5445D6' }];
export default function FinancialReportsPage() { return <PortalLayout><div className="report-page"><style>{styles}</style><div className="report-head"><div><p className="eyebrow">Reports / Finance</p><h1 className="report-title">Financial performance</h1><p className="report-subtitle">Review revenue, COD collections, settlements, and payment health.</p></div><div className="report-actions"><select className="range-select" defaultValue="30"><option value="30">Last 30 days</option><option value="90">Last 90 days</option></select><ExportButton /></div></div><KpiDashboard metrics={metrics} /><div className="report-grid"><ReportChart title="Revenue trend" meta="Daily revenue (LKR)" data={[480,620,560,760,700,820,780]} labels={['Mon','Tue','Wed','Thu','Fri','Sat','Sun']} color="#0EA394" /><div className="report-panel"><h2 className="panel-title">Settlement status</h2><table><thead><tr><th>Status</th><th>Amount</th><th>Share</th></tr></thead><tbody>{[['Settled','Rs 7.2M','85.7%'],['Processing','Rs 1.2M','14.3%'],['Disputed','Rs 84K','1.0%'],['Refunded','Rs 42K','0.5%']].map((row) => <tr key={row[0]}><td>{row[0]}</td><td>{row[1]}</td><td className="good">{row[2]}</td></tr>)}</tbody></table></div></div><div className="report-panel"><h2 className="panel-title">Revenue by service</h2><table><thead><tr><th>Service</th><th>Revenue</th><th>Share</th><th>Growth</th></tr></thead><tbody>{[['Standard delivery','Rs 8.4M','45.2%','+11.4%'],['Same-day','Rs 5.1M','27.4%','+18.2%'],['Express','Rs 3.8M','20.4%','+14.8%'],['Returns and extras','Rs 1.3M','7.0%','+6.2%']].map((row) => <tr key={row[0]}>{row.map((value, index) => <td key={value} className={index > 1 ? 'good' : ''}>{value}</td>)}</tr>)}</tbody></table></div></div></PortalLayout>; }
