import React from 'react';
import { CheckCircle2, PackageOpen, Store, WalletCards } from 'lucide-react';
import PortalLayout from '../../components/layout/PortalLayout';
import KpiDashboard from '../../components/reports/KpiDashboard';
import ReportChart from '../../components/reports/ReportChart';
import ExportButton from '../../components/common/ExportButton';

const styles = `.report-page { display:grid; gap:20px; padding:24px; } .report-head { display:flex; align-items:flex-end; justify-content:space-between; gap:16px; } .eyebrow { margin:0 0 5px; color:#9AA1B4; font-size:12px; font-weight:700; letter-spacing:.08em; text-transform:uppercase; } .report-title { margin:0; color:#12213F; font:700 22px 'Sora',sans-serif; } .report-subtitle { margin:8px 0 0; color:#697086; font-size:13px; } .report-actions { display:flex; align-items:center; gap:9px; } .range-select { border:1px solid #E3E7EF; border-radius:10px; padding:10px 12px; background:#fff; color:#12213F; font-size:12px; } .report-grid { display:grid; grid-template-columns:1.2fr .8fr; gap:16px; } .report-panel { border:1px solid #E3E7EF; border-radius:14px; padding:18px 20px; background:#fff; } .panel-title { margin:0 0 14px; color:#12213F; font:700 14.5px 'Sora',sans-serif; } table { width:100%; border-collapse:collapse; } th { padding:0 10px 10px; color:#9AA1B4; font-size:11px; text-align:left; text-transform:uppercase; } td { padding:12px 10px; border-top:1px solid #E3E7EF; color:#12213F; font-size:12.5px; } .good { color:#0C8C6B; font-weight:700; } .muted { margin-top:3px; color:#697086; font-size:11px; } @media(max-width:850px){.report-page{padding:16px}.report-head{align-items:flex-start;flex-direction:column}.report-grid{grid-template-columns:1fr}}`;
const metrics = [{ label: 'Active merchants', value: '384', delta: '+24 this quarter', icon: Store }, { label: 'Merchant shipments', value: '12,486', delta: '+18.6% vs last period', icon: PackageOpen, iconBg: '#E8EFFE', iconColor: '#2453B8' }, { label: 'Merchant delivery rate', value: '97.2%', delta: '+1.4% improvement', icon: CheckCircle2, iconBg: '#E4F7F4', iconColor: '#0C8C6B' }, { label: 'COD collected', value: 'Rs 8.4M', delta: '+9.8% this month', icon: WalletCards, iconBg: '#FCEFD6', iconColor: '#8A5A05' }];
export default function MerchantReportsPage() { return <PortalLayout><div className="report-page"><style>{styles}</style><div className="report-head"><div><p className="eyebrow">Reports / Merchants</p><h1 className="report-title">Merchant performance</h1><p className="report-subtitle">Understand merchant volume, delivery outcomes, and collection activity.</p></div><div className="report-actions"><select className="range-select" defaultValue="30"><option value="30">Last 30 days</option><option value="90">Last 90 days</option></select><ExportButton /></div></div><KpiDashboard metrics={metrics} /><div className="report-grid"><ReportChart title="Merchant shipment volume" meta="Daily volume" data={[940,1080,1010,1240,1170,1320,1280]} labels={['Mon','Tue','Wed','Thu','Fri','Sat','Sun']} color="#7C6CF0" /><div className="report-panel"><h2 className="panel-title">Top merchants</h2><table><thead><tr><th>Merchant</th><th>Shipments</th><th>Success</th></tr></thead><tbody>{[['Island Retail Network','2,184','98.4%'],['Lanka Fresh Commerce','1,746','97.8%'],['Metro Parts Distribution','1,284','96.9%'],['Ceylon Homeware','964','96.4%']].map((row) => <tr key={row[0]}><td><div>{row[0]}</div><div className="muted">Business plan</div></td><td>{row[1]}</td><td className="good">{row[2]}</td></tr>)}</tbody></table></div></div><div className="report-panel"><h2 className="panel-title">Merchant service mix</h2><table><thead><tr><th>Service</th><th>Orders</th><th>Share</th><th>Avg. value</th></tr></thead><tbody>{[['Standard delivery','6,842','54.8%','Rs 1,180'],['Same-day','3,426','27.4%','Rs 1,620'],['Express','1,884','15.1%','Rs 2,080'],['Returns','334','2.7%','Rs 940']].map((row) => <tr key={row[0]}>{row.map((value, index) => <td key={value} className={index === 2 ? 'good' : ''}>{value}</td>)}</tr>)}</tbody></table></div></div></PortalLayout>; }
