import React from 'react';
import { Activity, CheckCircle2, Clock3, PackageCheck } from 'lucide-react';
import PortalLayout from '../../components/layout/PortalLayout';
import KpiDashboard from '../../components/reports/KpiDashboard';
import ReportChart from '../../components/reports/ReportChart';
import ExportButton from '../../components/common/ExportButton';

const styles = `
	.report-page { display: grid; gap: 20px; padding: 24px; } .report-head { display: flex; align-items: flex-end; justify-content: space-between; gap: 16px; } .eyebrow { margin: 0 0 5px; color: #9AA1B4; font-size: 12px; font-weight: 700; letter-spacing: .08em; text-transform: uppercase; } .report-title { margin: 0; color: #12213F; font: 700 22px 'Sora', sans-serif; } .report-subtitle { margin: 8px 0 0; color: #697086; font-size: 13px; } .report-actions { display: flex; align-items: center; gap: 9px; } .range-select { border: 1px solid #E3E7EF; border-radius: 10px; padding: 10px 12px; background: #fff; color: #12213F; font-size: 12px; } .report-grid { display: grid; grid-template-columns: 1.2fr .8fr; gap: 16px; } .report-panel { border: 1px solid #E3E7EF; border-radius: 14px; padding: 18px 20px; background: #fff; } .panel-title { margin: 0 0 14px; color: #12213F; font: 700 14.5px 'Sora', sans-serif; } table { width: 100%; border-collapse: collapse; } th { padding: 0 10px 10px; color: #9AA1B4; font-size: 11px; text-align: left; text-transform: uppercase; } td { padding: 12px 10px; border-top: 1px solid #E3E7EF; color: #12213F; font-size: 12.5px; } .good { color: #0C8C6B; font-weight: 700; } .muted { margin-top: 3px; color: #697086; font-size: 11px; } @media (max-width: 850px) { .report-page { padding: 16px; } .report-head { align-items: flex-start; flex-direction: column; } .report-grid { grid-template-columns: 1fr; } }
`;

const metrics = [{ label: 'Shipments processed', value: '8,642', delta: '+12.8% vs last period', icon: PackageCheck }, { label: 'On-time delivery', value: '96.8%', delta: '+2.1% improvement', icon: CheckCircle2, iconBg: '#E4F7F4', iconColor: '#0C8C6B' }, { label: 'Average delivery time', value: '2.4 days', delta: '-0.3 days faster', positive: true, icon: Clock3, iconBg: '#FCEFD6', iconColor: '#8A5A05' }, { label: 'Failed delivery rate', value: '2.8%', delta: '-0.6% improvement', icon: Activity, iconBg: '#EEECFE', iconColor: '#5445D6' }];

export default function OperationalReportsPage() { return <PortalLayout><div className="report-page"><style>{styles}</style><div className="report-head"><div><p className="eyebrow">Reports / Operations</p><h1 className="report-title">Operational performance</h1><p className="report-subtitle">Track network throughput, delivery quality, and operational efficiency.</p></div><div className="report-actions"><select className="range-select" defaultValue="30"><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="90">Last 90 days</option></select><ExportButton /></div></div><KpiDashboard metrics={metrics} /><div className="report-grid"><ReportChart title="Shipment volume" meta="Daily shipments" data={[620, 740, 680, 820, 790, 920, 860]} labels={['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']} /><div className="report-panel"><h2 className="panel-title">Service quality by status</h2><table><thead><tr><th>Status</th><th>Shipments</th><th>Share</th></tr></thead><tbody>{[['Delivered', '7,820', '90.5%'], ['In transit', '496', '5.7%'], ['Delayed', '242', '2.8%'], ['Failed', '84', '1.0%']].map(([status, count, share]) => <tr key={status}><td>{status}</td><td>{count}</td><td className="good">{share}</td></tr>)}</tbody></table></div></div><div className="report-panel"><h2 className="panel-title">Operational zones</h2><table><thead><tr><th>Zone</th><th>Shipments</th><th>On-time rate</th><th>Avg. duration</th></tr></thead><tbody>{[['Colombo Metro', '3,420', '98.1%', '1.6 days'], ['Central Province', '2,180', '95.4%', '2.5 days'], ['Southern Coast', '1,884', '96.2%', '2.2 days'], ['Northern Region', '1,158', '94.8%', '3.1 days']].map((row) => <tr key={row[0]}>{row.map((value, index) => <td key={value} className={index === 2 ? 'good' : ''}>{value}</td>)}</tr>)}</tbody></table></div></div></PortalLayout>; }
