import React, { useState } from 'react';
import { ArrowRight, CheckCircle2, Package, Search, UserRound } from 'lucide-react';
import PortalLayout from '../../components/layout/PortalLayout';

const styles = `.counter-page{display:grid;gap:20px;padding:24px}.counter-head{display:flex;align-items:center;justify-content:space-between;gap:16px}.eyebrow{margin:0 0 5px;color:#9AA1B4;font-size:12px;font-weight:700;letter-spacing:.08em;text-transform:uppercase}.page-title{margin:0;color:#12213F;font:700 22px 'Sora',sans-serif}.page-subtitle{margin:8px 0 0;color:#697086;font-size:13px}.counter-panel{max-width:900px;border:1px solid #E3E7EF;border-radius:14px;background:#fff;padding:22px}.search-form{display:flex;gap:9px}.search-input{display:flex;align-items:center;gap:9px;flex:1;border:1px solid #E3E7EF;border-radius:10px;padding:0 12px;background:#F9FAFC;color:#9AA1B4}.search-input input{width:100%;border:0;outline:0;background:transparent;color:#12213F;padding:12px 0;font-size:13px}.search-button,.next-button{display:inline-flex;align-items:center;gap:8px;border:1px solid #12213F;border-radius:10px;padding:10px 14px;background:#12213F;color:#fff;font-size:12px;font-weight:700;cursor:pointer}.result-card{margin-top:20px;padding:18px;border:1px solid #BCEBE3;border-radius:12px;background:#F3FCFA}.result-head{display:flex;align-items:center;justify-content:space-between;gap:10px}.result-title{margin:0;color:#12213F;font:700 15px 'Sora',sans-serif}.result-status{display:inline-flex;align-items:center;gap:6px;color:#0C8C6B;font-size:11px;font-weight:700}.result-status svg{color:#0C8C6B}.result-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-top:16px}.result-item{padding-top:12px;border-top:1px solid #D7F0EB}.result-label{color:#697086;font-size:10.5px;text-transform:uppercase;letter-spacing:.04em}.result-value{margin-top:5px;color:#12213F;font-size:13px;font-weight:700}.result-actions{display:flex;justify-content:flex-end;margin-top:18px}@media(max-width:600px){.counter-page{padding:16px}.counter-head{align-items:flex-start;flex-direction:column}.search-form{flex-direction:column}.search-button{justify-content:center}.result-grid{grid-template-columns:1fr}}`;

const shipment = { id: 'SH-28491', sender: 'Urban Mart', recipient: 'Pasan Perera', route: 'Colombo 07 → Kandy City', status: 'In transit', cod: 'Rs 1,250' };

export default function SearchShipmentPage() {
	const [query, setQuery] = useState('SH-28491');
	const [searched, setSearched] = useState(false);
	return <PortalLayout><div className="counter-page"><style>{styles}</style><div className="counter-head"><div><p className="eyebrow">Counter operations</p><h1 className="page-title">Search shipment</h1><p className="page-subtitle">Find a shipment quickly to start pickup, payment, or label workflows.</p></div></div><div className="counter-panel"><form className="search-form" onSubmit={(event)=>{event.preventDefault();setSearched(true);}}><div className="search-input"><Search size={16}/><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Tracking number, phone, or customer" aria-label="Shipment search" /></div><button type="submit" className="search-button">Search shipment</button></form>{searched ? <div className="result-card"><div className="result-head"><h2 className="result-title">Shipment found</h2><span className="result-status"><CheckCircle2 size={14}/> {shipment.status}</span></div><div className="result-grid"><div className="result-item"><div className="result-label">Tracking number</div><div className="result-value"><Package size={13} style={{verticalAlign:'middle',marginRight:5}}/>{shipment.id}</div></div><div className="result-item"><div className="result-label">Customer</div><div className="result-value"><UserRound size={13} style={{verticalAlign:'middle',marginRight:5}}/>{shipment.recipient}</div></div><div className="result-item"><div className="result-label">Route</div><div className="result-value">{shipment.route}</div></div><div className="result-item"><div className="result-label">Sender</div><div className="result-value">{shipment.sender}</div></div><div className="result-item"><div className="result-label">COD amount</div><div className="result-value">{shipment.cod}</div></div><div className="result-item"><div className="result-label">Search match</div><div className="result-value">{query || shipment.id}</div></div></div><div className="result-actions"><button type="button" className="next-button">Continue workflow <ArrowRight size={14}/></button></div></div> : null}</div></div></PortalLayout>;
}
