import React from 'react';
import { Bell, Mail, MessageSquare, Plus, Smartphone } from 'lucide-react';
import PortalLayout from '../../components/layout/PortalLayout';
import TemplateEditor from '../../components/notifications/TemplateEditor';
import NotificationBell from '../../components/notifications/NotificationBell';

const styles = `.templates-page{display:grid;gap:20px;padding:24px}.templates-head{display:flex;align-items:center;justify-content:space-between;gap:16px}.eyebrow{margin:0 0 5px;color:#9AA1B4;font-size:12px;font-weight:700;letter-spacing:.08em;text-transform:uppercase}.page-title{margin:0;color:#12213F;font:700 22px 'Sora',sans-serif}.page-subtitle{margin:8px 0 0;color:#697086;font-size:13px}.templates-actions{display:flex;align-items:center;gap:10px}.primary-btn{display:inline-flex;align-items:center;gap:8px;border:1px solid #12213F;border-radius:10px;padding:10px 14px;background:#12213F;color:#fff;font-size:12px;font-weight:700;cursor:pointer}.template-content{display:grid;grid-template-columns:1.15fr .85fr;gap:16px;align-items:start}.template-panel{border:1px solid #E3E7EF;border-radius:14px;background:#fff;padding:18px 20px;overflow-x:auto}.panel-title{margin:0 0 14px;color:#12213F;font:700 14.5px 'Sora',sans-serif}table{width:100%;border-collapse:collapse;min-width:560px}th{padding:0 12px 10px;color:#9AA1B4;font-size:11px;text-align:left;text-transform:uppercase}td{padding:13px 12px;border-top:1px solid #E3E7EF;color:#12213F;font-size:13px}.template-name{font-weight:700}.muted{margin-top:3px;color:#697086;font-size:11.5px}.channel{display:inline-flex;align-items:center;gap:6px;padding:5px 8px;border-radius:999px;background:#E8EFFE;color:#2453B8;font-size:11px;font-weight:700}.status{display:inline-flex;align-items:center;gap:6px;padding:5px 8px;border-radius:999px;background:#E4F7F4;color:#0C8C6B;font-size:11px;font-weight:700}.status::before{content:'';width:6px;height:6px;border-radius:50%;background:currentColor}.edit-btn{border:1px solid #E3E7EF;border-radius:8px;padding:6px 9px;background:#fff;color:#12213F;font-size:11px;font-weight:700;cursor:pointer}@media(max-width:950px){.templates-page{padding:16px}.templates-head{align-items:flex-start;flex-direction:column}.template-content{grid-template-columns:1fr}}`;
const templates = [{name:'Shipment delivered',channel:'Email',event:'shipment.delivered',updated:'Today',status:'Active'},{name:'Out for delivery',channel:'SMS',event:'shipment.out_for_delivery',updated:'Yesterday',status:'Active'},{name:'COD collection reminder',channel:'WhatsApp',event:'cod.collection_due',updated:'12 Aug 2026',status:'Active'},{name:'Delivery failed',channel:'Push',event:'shipment.failed',updated:'08 Aug 2026',status:'Draft'}];
const channelIcon = {Email:Mail,SMS:Smartphone,WhatsApp:MessageSquare,Push:Bell};
export default function NotificationTemplatesPage(){return <PortalLayout><div className="templates-page"><style>{styles}</style><div className="templates-head"><div><p className="eyebrow">Settings / Notifications</p><h1 className="page-title">Notification templates</h1><p className="page-subtitle">Manage the messages customers, drivers, and merchants receive during shipment events.</p></div><div className="templates-actions"><NotificationBell /><button type="button" className="primary-btn"><Plus size={14}/> New template</button></div></div><div className="template-content"><div className="template-panel"><h2 className="panel-title">Template library</h2><table><thead><tr><th>Template</th><th>Channel</th><th>Event</th><th>Updated</th><th>Status</th><th/></tr></thead><tbody>{templates.map((template)=>{const Icon=channelIcon[template.channel]||Bell;return <tr key={template.name}><td><div className="template-name">{template.name}</div><div className="muted">Customer communication</div></td><td><span className="channel"><Icon size={12}/>{template.channel}</span></td><td>{template.event}</td><td>{template.updated}</td><td><span className="status">{template.status}</span></td><td><button type="button" className="edit-btn">Edit</button></td></tr>})}</tbody></table></div><TemplateEditor /></div></div></PortalLayout>}
