import React, { useState } from 'react';
import { Camera, Check, Mail, Phone, Save, ShieldCheck } from 'lucide-react';
import PortalLayout from '../../components/layout/PortalLayout';
import NotificationBell from '../../components/notifications/NotificationBell';

const styles = `.profile-page{display:grid;gap:20px;padding:24px}.profile-head{display:flex;align-items:center;justify-content:space-between;gap:16px}.eyebrow{margin:0 0 5px;color:#9AA1B4;font-size:12px;font-weight:700;letter-spacing:.08em;text-transform:uppercase}.page-title{margin:0;color:#12213F;font:700 22px 'Sora',sans-serif}.page-subtitle{margin:8px 0 0;color:#697086;font-size:13px}.profile-actions{display:flex;align-items:center;gap:10px}.save-btn{display:inline-flex;align-items:center;gap:8px;border:1px solid #12213F;border-radius:10px;padding:10px 14px;background:#12213F;color:#fff;font-size:12px;font-weight:700;cursor:pointer}.profile-grid{display:grid;grid-template-columns:.7fr 1.3fr;gap:16px;align-items:start}.profile-card,.profile-form{border:1px solid #E3E7EF;border-radius:14px;background:#fff;padding:20px}.profile-card{text-align:center}.avatar{width:80px;height:80px;display:grid;place-items:center;margin:0 auto 12px;border-radius:22px;background:#7C6CF0;color:#fff;font:800 25px 'Sora',sans-serif}.profile-name{margin:0;color:#12213F;font:700 16px 'Sora',sans-serif}.profile-role{margin:5px 0 16px;color:#697086;font-size:12px}.profile-contact{display:grid;gap:10px;padding-top:15px;border-top:1px solid #E3E7EF;text-align:left}.contact-row{display:flex;align-items:center;gap:9px;color:#697086;font-size:12px}.contact-row svg{color:#3E7BFA}.verification{display:flex;align-items:center;justify-content:center;gap:6px;margin-top:18px;padding:9px;border-radius:9px;background:#E4F7F4;color:#087367;font-size:11px;font-weight:700}.profile-form h2{margin:0 0 18px;color:#12213F;font:700 15px 'Sora',sans-serif}.form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.field{display:grid;gap:7px}.field.full{grid-column:1/-1}.field label{color:#697086;font-size:11px;font-weight:700;letter-spacing:.04em;text-transform:uppercase}.field input,.field select,.field textarea{width:100%;border:1px solid #E3E7EF;border-radius:10px;background:#F9FAFC;color:#12213F;padding:10px 12px;font-size:13px;outline:none}.field textarea{min-height:80px;resize:vertical}.field input:focus,.field select:focus,.field textarea:focus{border-color:#3E7BFA;box-shadow:0 0 0 3px rgba(62,123,250,.12)}@media(max-width:760px){.profile-page{padding:16px}.profile-head{align-items:flex-start;flex-direction:column}.profile-grid{grid-template-columns:1fr}}@media(max-width:560px){.form-grid{grid-template-columns:1fr}.field.full{grid-column:auto}}`;

export default function ProfileSettingsPage() {
	const [profile, setProfile] = useState({ name: 'Nayani Rathnayake', email: 'nayani@egotech.com', phone: '077 123 4567', branch: 'Colombo Central', bio: 'Platform administrator focused on reliable courier operations.' });
	const update = (event) => setProfile((current) => ({ ...current, [event.target.name]: event.target.value }));
	return <PortalLayout><div className="profile-page"><style>{styles}</style><div className="profile-head"><div><p className="eyebrow">Settings / Account</p><h1 className="page-title">Profile settings</h1><p className="page-subtitle">Keep your contact details and administrator profile up to date.</p></div><div className="profile-actions"><NotificationBell /><button type="button" className="save-btn"><Save size={14} /> Save profile</button></div></div><div className="profile-grid"><div className="profile-card"><div className="avatar">NR</div><h2 className="profile-name">{profile.name}</h2><p className="profile-role">Operations Administrator</p><button type="button" className="save-btn" style={{ background: '#fff', color: '#12213F', borderColor: '#E3E7EF' }}><Camera size={14} /> Change photo</button><div className="profile-contact"><div className="contact-row"><Mail size={14} />{profile.email}</div><div className="contact-row"><Phone size={14} />{profile.phone}</div></div><div className="verification"><ShieldCheck size={14} /> Account verified</div></div><div className="profile-form"><h2>Personal information</h2><div className="form-grid"><div className="field full"><label htmlFor="profile-name">Full name</label><input id="profile-name" name="name" value={profile.name} onChange={update} /></div><div className="field"><label htmlFor="profile-email">Email address</label><input id="profile-email" name="email" type="email" value={profile.email} onChange={update} /></div><div className="field"><label htmlFor="profile-phone">Phone number</label><input id="profile-phone" name="phone" value={profile.phone} onChange={update} /></div><div className="field"><label htmlFor="profile-branch">Primary branch</label><select id="profile-branch" name="branch" value={profile.branch} onChange={update}><option>Colombo Central</option><option>Kandy Operations</option><option>Galle South</option></select></div><div className="field"><label htmlFor="profile-language">Language</label><select id="profile-language" defaultValue="English"><option>English</option><option>Sinhala</option><option>Tamil</option></select></div><div className="field full"><label htmlFor="profile-bio">About</label><textarea id="profile-bio" name="bio" value={profile.bio} onChange={update} /></div></div></div></div></div></PortalLayout>;
}
