import React from 'react';
import { Globe2, MapPin, Plus, Route } from 'lucide-react';
import PortalLayout from '../../components/layout/PortalLayout';
import ZoneForm from '../../components/pricing/ZoneForm';
import ServiceabilityChecker from '../../components/pricing/ServiceabilityChecker';

const styles = `.zone-page{display:grid;gap:20px;padding:24px}.zone-head{display:flex;align-items:center;justify-content:space-between;gap:16px}.eyebrow{margin:0 0 5px;color:#9AA1B4;font-size:12px;font-weight:700;letter-spacing:.08em;text-transform:uppercase}.page-title{margin:0;color:#12213F;font:700 22px 'Sora',sans-serif}.page-subtitle{margin:8px 0 0;color:#697086;font-size:13px}.primary-btn{display:inline-flex;align-items:center;gap:8px;border:1px solid #12213F;border-radius:10px;padding:10px 14px;background:#12213F;color:#fff;font-size:12px;font-weight:700;cursor:pointer}.zone-content{display:grid;grid-template-columns:1.15fr .85fr;gap:16px;align-items:start}.zone-panel{border:1px solid #E3E7EF;border-radius:14px;background:#fff;padding:18px 20px;overflow-x:auto}.panel-title{margin:0 0 14px;color:#12213F;font:700 14.5px 'Sora',sans-serif}table{width:100%;border-collapse:collapse;min-width:560px}th{padding:0 12px 10px;color:#9AA1B4;font-size:11px;text-align:left;text-transform:uppercase}td{padding:13px 12px;border-top:1px solid #E3E7EF;color:#12213F;font-size:13px}.zone-name{font-weight:700}.muted{margin-top:3px;color:#697086;font-size:11.5px}.status{display:inline-flex;align-items:center;gap:6px;border-radius:999px;padding:5px 9px;background:#E4F7F4;color:#0C8C6B;font-size:11px;font-weight:700}.status::before{content:'';width:6px;height:6px;border-radius:50%;background:currentColor}.edit-btn{border:1px solid #E3E7EF;border-radius:8px;padding:6px 9px;background:#fff;color:#12213F;font-size:11px;font-weight:700;cursor:pointer}.zone-side{display:grid;gap:16px}.zone-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.zone-stat{padding:15px;border:1px solid #E3E7EF;border-radius:12px;background:#fff}.zone-stat-label{color:#697086;font-size:11px;font-weight:600}.zone-stat-value{margin-top:7px;color:#12213F;font:800 22px 'Sora',sans-serif}.zone-stat-note{margin-top:4px;color:#0C8C6B;font-size:11px;font-weight:600}@media(max-width:950px){.zone-page{padding:16px}.zone-head{align-items:flex-start;flex-direction:column}.zone-content{grid-template-columns:1fr}}@media(max-width:560px){.zone-stats{grid-template-columns:1fr}}`;
const zones = [{name:'Colombo Metro',code:'COL-MET',type:'Metro',postal:'00100 - 01500',shipments:'3,420',status:'Active'},{name:'Central Province',code:'CEN-REG',type:'Regional',postal:'20000 - 22200',shipments:'2,180',status:'Active'},{name:'Southern Coast',code:'SOU-REG',type:'Regional',postal:'80000 - 82500',shipments:'1,884',status:'Active'},{name:'Northern Region',code:'NOR-REM',type:'Remote',postal:'40000 - 43000',shipments:'1,158',status:'Paused'}];
export default function ZoneSettingsPage(){return <PortalLayout><div className="zone-page"><style>{styles}</style><div className="zone-head"><div><p className="eyebrow">Settings / Pricing</p><h1 className="page-title">Service zones</h1><p className="page-subtitle">Define delivery coverage, postal code ranges, and zone-level surcharges.</p></div><button type="button" className="primary-btn"><Plus size={14}/> Add zone</button></div><div className="zone-stats">{[['Active zones','18','4 regional zones',Globe2],['Postal coverage','92%','Of serviceable addresses',MapPin],['Routes mapped','42','Ready for dispatch',Route]].map(([label,value,note,Icon])=><div className="zone-stat" key={label}><div className="zone-stat-label"><Icon size={13} style={{verticalAlign:'middle',marginRight:5}}/>{label}</div><div className="zone-stat-value">{value}</div><div className="zone-stat-note">{note}</div></div>)}</div><div className="zone-content"><div className="zone-panel"><h2 className="panel-title">Coverage directory</h2><table><thead><tr><th>Zone</th><th>Type</th><th>Postal range</th><th>Shipments</th><th>Status</th><th/></tr></thead><tbody>{zones.map((zone)=><tr key={zone.code}><td><div className="zone-name">{zone.name}</div><div className="muted">{zone.code}</div></td><td>{zone.type}</td><td>{zone.postal}</td><td>{zone.shipments}</td><td><span className="status">{zone.status}</span></td><td><button type="button" className="edit-btn">Edit</button></td></tr>)}</tbody></table></div><div className="zone-side"><ZoneForm /><ServiceabilityChecker /></div></div></div></PortalLayout>}
